pipeline {
    agent any
    tools {
        maven 'Maven 3.6.1'
    }
    stages {
        stage('build') {
            steps {
                echo "Compiling work app"
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
            steps {
                echo 'Running unit tests on work app'
                dir('worker') {
                    sh 'mvn clean test'

                }
            }
        }

        stage('package') {
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
}

post {
    always {
        echo 'Buil pipeline for worker is complete'
    }
}
}