pipeline {
    agent none
    stages {
        stage('build') {
    agent {
        docker {
            image 'maven:3.6.1-jdk-8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
            when {
                changeset '**/worker/**'
            }
            steps {
                slackSend channel: "#jenkins", message: "Build started - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
                echo "Compiling work app"
                dir('worker') {
                    sh 'mvn compile'
                }
            }
        }
        stage('test') {
    agent {
        docker {
            image 'maven:3.6.1-jdk-8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Running unit tests on work app'
                dir('worker') {
                    sh 'mvn clean test'

                }
            }
        }

        stage('package') {
    agent {
        docker {
            image 'maven:3.6.1-jdk-8-alpine'
            args '-v $HOME/.m2:/root/.m2'
        }
    }
            when {
                branch 'master'
                changeset '**/worker/**'
            }
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                    sh 'mvn package -DskipTests'
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }

        stage('docker-package') {
	agent any
            when {
                changeset '**/worker/**'
            }
            steps {
                echo 'Packaging worker app with docker'
		script {
		withDockerRegistry(credentialsId: 'gabrielonjas', url: 'https://index.docker.io') {
		def workerImage = docker.build("galtamirano/worker:v${env.BUILD_ID}","./worker")
		workerImage.push()
		workerImage.push("${env.BRANCH_NAME}")
			}
		}
            }
    }
}

    post {
        always {
            echo 'Buil pipeline for worker is complete'
        }
        failure {
            slackSend channel: "#jenkins", message: "Build failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
        success {
            slackSend channel: "#jenkins", message: "Build succeeded - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
        }
    }
}
